[project]
name = "hurtownie-danych"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "scrapy>=2.19.0",
]

[project.scripts]
hurtownie-danych = "hurtownie_danych:main"

[build-system]
requires = ["uv_build>=0.12.24,<0.13.0"]
build-backend = "uv_build"
